# Generated by Django 4.2.14 on 2024-08-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_recipe_author_remove_recipe_cook_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tag",
            field=models.CharField(
                choices=[
                    ("LACTOSEFREE", "Lactose-free"),
                    ("VEGAN", "Vegan"),
                    ("GLUTEN_FREE", "Gluten-Free"),
                    ("KETO", "Keto"),
                ],
                default="recipe",
                max_length=100,
            ),
        ),
    ]
