# Generated by Django 4.2.14 on 2024-08-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_recipe_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default="unpublished"
            ),
        ),
    ]
